<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
 <!-- the fixed joint for the support is at the top of the base-->
  <xacro:property name="base_height"   value="0.195"/>
  <xacro:property name="robot_height"   value="1.8"/>
  <xacro:property name="support_mass"   value="2"/>
  <xacro:property name="support_x"   value="0.3"/> <!-- support length on x-->
  <xacro:property name="support_y"   value="0.15"/> <!-- support length on y-->
  <xacro:property name="support_z"   value="${robot_height-base_height}"/> <!-- support height-->

  <xacro:macro name="support" params="name parent">

	<link name="${name}_link">
       <inertial>
        <origin xyz="0 0 ${support_z/2}" rpy="0 0 0"/>
        <mass value="${support_mass}"/>
        <inertia ixx="${1/12*support_mass*(support_y*support_y+support_z*support_z)}" ixy="0.0" ixz="0.0"
                 iyy="${1/12*support_mass*(support_x*support_x+support_z*support_z)}" iyz="0.0"
                 izz="${1/12*support_mass*(support_x*support_x+support_y*support_y)}"/>
      </inertial>
		<visual>
		  <origin xyz="0 0 ${support_z/2}" rpy="0 0 0"/>
		  <geometry>      
		    <box size="${support_x} ${support_y} ${support_z}"/>
		  </geometry>
		</visual>
      <collision>
  		  <origin xyz="0 0 ${support_z/2}" rpy="0 0 0"/>
		  <geometry>      
		    <box size="${support_x} ${support_y} ${support_z}"/>
		  </geometry>
      </collision>
	  </link>

    <joint name="support_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}_link"/>
      <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
    </joint>


    <gazebo reference="${name}_link">
      <material>Gazebo/Red</material>
    </gazebo>
  </xacro:macro>
</robot>
